services:
  - type: web
    name: mobilador-server
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /api/health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PUBLIC_URL
        fromService:
          name: mobilador-server
          type: web
          property: host
